// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: analytics.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDailyVisitors = `-- name: GetDailyVisitors :many
SELECT 
    DATE_TRUNC('day', created_at)::date AS date,
    COUNT(DISTINCT ip_hash)::bigint AS count
FROM analytics_pageviews
WHERE created_at >= NOW() - INTERVAL '30 days'
GROUP BY 1
ORDER BY 1 ASC
`

type GetDailyVisitorsRow struct {
	Date  pgtype.Date `json:"date"`
	Count int64       `json:"count"`
}

func (q *Queries) GetDailyVisitors(ctx context.Context) ([]GetDailyVisitorsRow, error) {
	rows, err := q.db.Query(ctx, getDailyVisitors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDailyVisitorsRow{}
	for rows.Next() {
		var i GetDailyVisitorsRow
		if err := rows.Scan(&i.Date, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPageViewsByUrl = `-- name: GetPageViewsByUrl :many
SELECT 
    page_url,
    COUNT(*)::bigint AS views,
    COUNT(DISTINCT ip_hash)::bigint AS unique_visitors
FROM analytics_pageviews
WHERE created_at >= NOW() - INTERVAL '30 days'
GROUP BY page_url
ORDER BY views DESC
`

type GetPageViewsByUrlRow struct {
	PageUrl        string `json:"page_url"`
	Views          int64  `json:"views"`
	UniqueVisitors int64  `json:"unique_visitors"`
}

func (q *Queries) GetPageViewsByUrl(ctx context.Context) ([]GetPageViewsByUrlRow, error) {
	rows, err := q.db.Query(ctx, getPageViewsByUrl)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPageViewsByUrlRow{}
	for rows.Next() {
		var i GetPageViewsByUrlRow
		if err := rows.Scan(&i.PageUrl, &i.Views, &i.UniqueVisitors); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentPageViews = `-- name: GetRecentPageViews :many
SELECT id, page_url, referrer, ip_hash, user_agent, utm_source, utm_medium, utm_campaign, created_at FROM analytics_pageviews 
ORDER BY created_at DESC 
LIMIT $1 OFFSET $2
`

type GetRecentPageViewsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetRecentPageViews(ctx context.Context, arg GetRecentPageViewsParams) ([]AnalyticsPageview, error) {
	rows, err := q.db.Query(ctx, getRecentPageViews, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnalyticsPageview{}
	for rows.Next() {
		var i AnalyticsPageview
		if err := rows.Scan(
			&i.ID,
			&i.PageUrl,
			&i.Referrer,
			&i.IpHash,
			&i.UserAgent,
			&i.UtmSource,
			&i.UtmMedium,
			&i.UtmCampaign,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalPageViews = `-- name: GetTotalPageViews :one
SELECT COUNT(*)::bigint FROM analytics_pageviews
`

func (q *Queries) GetTotalPageViews(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalPageViews)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getTotalVisitors = `-- name: GetTotalVisitors :one
SELECT COUNT(DISTINCT ip_hash)::bigint FROM analytics_pageviews
`

func (q *Queries) GetTotalVisitors(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalVisitors)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const recordPageView = `-- name: RecordPageView :exec
INSERT INTO analytics_pageviews (
    page_url, referrer, ip_hash, user_agent, utm_source, utm_medium, utm_campaign
) VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type RecordPageViewParams struct {
	PageUrl     string      `json:"page_url"`
	Referrer    pgtype.Text `json:"referrer"`
	IpHash      string      `json:"ip_hash"`
	UserAgent   pgtype.Text `json:"user_agent"`
	UtmSource   pgtype.Text `json:"utm_source"`
	UtmMedium   pgtype.Text `json:"utm_medium"`
	UtmCampaign pgtype.Text `json:"utm_campaign"`
}

func (q *Queries) RecordPageView(ctx context.Context, arg RecordPageViewParams) error {
	_, err := q.db.Exec(ctx, recordPageView,
		arg.PageUrl,
		arg.Referrer,
		arg.IpHash,
		arg.UserAgent,
		arg.UtmSource,
		arg.UtmMedium,
		arg.UtmCampaign,
	)
	return err
}
