// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: anomaly_logs.sql

package repository

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccessLog = `-- name: CreateAccessLog :exec
INSERT INTO access_logs (user_id, session_id, ip, endpoint, method, status_code)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateAccessLogParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	SessionID  pgtype.UUID `json:"session_id"`
	Ip         *netip.Addr `json:"ip"`
	Endpoint   pgtype.Text `json:"endpoint"`
	Method     pgtype.Text `json:"method"`
	StatusCode pgtype.Int4 `json:"status_code"`
}

func (q *Queries) CreateAccessLog(ctx context.Context, arg CreateAccessLogParams) error {
	_, err := q.db.Exec(ctx, createAccessLog,
		arg.UserID,
		arg.SessionID,
		arg.Ip,
		arg.Endpoint,
		arg.Method,
		arg.StatusCode,
	)
	return err
}

const createAnomalyLog = `-- name: CreateAnomalyLog :one
INSERT INTO anomaly_logs (user_id, event, score_delta, detail)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, event, score_delta, detail, created_at
`

type CreateAnomalyLogParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	Event      string      `json:"event"`
	ScoreDelta int32       `json:"score_delta"`
	Detail     []byte      `json:"detail"`
}

func (q *Queries) CreateAnomalyLog(ctx context.Context, arg CreateAnomalyLogParams) (AnomalyLog, error) {
	row := q.db.QueryRow(ctx, createAnomalyLog,
		arg.UserID,
		arg.Event,
		arg.ScoreDelta,
		arg.Detail,
	)
	var i AnomalyLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Event,
		&i.ScoreDelta,
		&i.Detail,
		&i.CreatedAt,
	)
	return i, err
}

const listAnomalyLogsByUser = `-- name: ListAnomalyLogsByUser :many
SELECT id, user_id, event, score_delta, detail, created_at FROM anomaly_logs WHERE user_id = $1 ORDER BY created_at DESC LIMIT $2
`

type ListAnomalyLogsByUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
}

func (q *Queries) ListAnomalyLogsByUser(ctx context.Context, arg ListAnomalyLogsByUserParams) ([]AnomalyLog, error) {
	rows, err := q.db.Query(ctx, listAnomalyLogsByUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnomalyLog{}
	for rows.Next() {
		var i AnomalyLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Event,
			&i.ScoreDelta,
			&i.Detail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentAnomalies = `-- name: ListRecentAnomalies :many
SELECT al.id, al.user_id, al.event, al.score_delta, al.detail, al.created_at, u.email, u.name, u.anomaly_score
FROM anomaly_logs al
JOIN users u ON u.id = al.user_id
ORDER BY al.created_at DESC LIMIT $1 OFFSET $2
`

type ListRecentAnomaliesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListRecentAnomaliesRow struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	Event        string             `json:"event"`
	ScoreDelta   int32              `json:"score_delta"`
	Detail       []byte             `json:"detail"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	Email        string             `json:"email"`
	Name         pgtype.Text        `json:"name"`
	AnomalyScore pgtype.Int4        `json:"anomaly_score"`
}

func (q *Queries) ListRecentAnomalies(ctx context.Context, arg ListRecentAnomaliesParams) ([]ListRecentAnomaliesRow, error) {
	rows, err := q.db.Query(ctx, listRecentAnomalies, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentAnomaliesRow{}
	for rows.Next() {
		var i ListRecentAnomaliesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Event,
			&i.ScoreDelta,
			&i.Detail,
			&i.CreatedAt,
			&i.Email,
			&i.Name,
			&i.AnomalyScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
