// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feedback.sql

package repository

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUnreadFeedback = `-- name: CountUnreadFeedback :one
SELECT COUNT(*) FROM feedback WHERE is_read = FALSE
`

func (q *Queries) CountUnreadFeedback(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadFeedback)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFeedback = `-- name: CreateFeedback :one
INSERT INTO feedback (user_email, user_role, category, rating, message, page_url, user_agent, ip)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_email, user_role, category, rating, message, page_url, user_agent, ip, is_read, created_at
`

type CreateFeedbackParams struct {
	UserEmail string      `json:"user_email"`
	UserRole  string      `json:"user_role"`
	Category  string      `json:"category"`
	Rating    pgtype.Int2 `json:"rating"`
	Message   string      `json:"message"`
	PageUrl   pgtype.Text `json:"page_url"`
	UserAgent pgtype.Text `json:"user_agent"`
	Ip        *netip.Addr `json:"ip"`
}

func (q *Queries) CreateFeedback(ctx context.Context, arg CreateFeedbackParams) (Feedback, error) {
	row := q.db.QueryRow(ctx, createFeedback,
		arg.UserEmail,
		arg.UserRole,
		arg.Category,
		arg.Rating,
		arg.Message,
		arg.PageUrl,
		arg.UserAgent,
		arg.Ip,
	)
	var i Feedback
	err := row.Scan(
		&i.ID,
		&i.UserEmail,
		&i.UserRole,
		&i.Category,
		&i.Rating,
		&i.Message,
		&i.PageUrl,
		&i.UserAgent,
		&i.Ip,
		&i.IsRead,
		&i.CreatedAt,
	)
	return i, err
}

const getFeedbackStats = `-- name: GetFeedbackStats :one
SELECT
  COUNT(*) AS total,
  COUNT(*) FILTER (WHERE is_read = FALSE) AS unread,
  COUNT(*) FILTER (WHERE category = 'saran') AS saran_count,
  COUNT(*) FILTER (WHERE category = 'bug') AS bug_count,
  COUNT(*) FILTER (WHERE category = 'pertanyaan') AS tanya_count,
  ROUND(AVG(rating)::numeric, 1) AS avg_rating
FROM feedback
`

type GetFeedbackStatsRow struct {
	Total      int64          `json:"total"`
	Unread     int64          `json:"unread"`
	SaranCount int64          `json:"saran_count"`
	BugCount   int64          `json:"bug_count"`
	TanyaCount int64          `json:"tanya_count"`
	AvgRating  pgtype.Numeric `json:"avg_rating"`
}

func (q *Queries) GetFeedbackStats(ctx context.Context) (GetFeedbackStatsRow, error) {
	row := q.db.QueryRow(ctx, getFeedbackStats)
	var i GetFeedbackStatsRow
	err := row.Scan(
		&i.Total,
		&i.Unread,
		&i.SaranCount,
		&i.BugCount,
		&i.TanyaCount,
		&i.AvgRating,
	)
	return i, err
}

const listFeedback = `-- name: ListFeedback :many
SELECT id, user_email, user_role, category, rating, message, page_url, user_agent, ip, is_read, created_at FROM feedback ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListFeedbackParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListFeedback(ctx context.Context, arg ListFeedbackParams) ([]Feedback, error) {
	rows, err := q.db.Query(ctx, listFeedback, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Feedback{}
	for rows.Next() {
		var i Feedback
		if err := rows.Scan(
			&i.ID,
			&i.UserEmail,
			&i.UserRole,
			&i.Category,
			&i.Rating,
			&i.Message,
			&i.PageUrl,
			&i.UserAgent,
			&i.Ip,
			&i.IsRead,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeedbackByCategory = `-- name: ListFeedbackByCategory :many
SELECT id, user_email, user_role, category, rating, message, page_url, user_agent, ip, is_read, created_at FROM feedback WHERE category = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListFeedbackByCategoryParams struct {
	Category string `json:"category"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

func (q *Queries) ListFeedbackByCategory(ctx context.Context, arg ListFeedbackByCategoryParams) ([]Feedback, error) {
	rows, err := q.db.Query(ctx, listFeedbackByCategory, arg.Category, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Feedback{}
	for rows.Next() {
		var i Feedback
		if err := rows.Scan(
			&i.ID,
			&i.UserEmail,
			&i.UserRole,
			&i.Category,
			&i.Rating,
			&i.Message,
			&i.PageUrl,
			&i.UserAgent,
			&i.Ip,
			&i.IsRead,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnreadFeedback = `-- name: ListUnreadFeedback :many
SELECT id, user_email, user_role, category, rating, message, page_url, user_agent, ip, is_read, created_at FROM feedback WHERE is_read = FALSE ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListUnreadFeedbackParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUnreadFeedback(ctx context.Context, arg ListUnreadFeedbackParams) ([]Feedback, error) {
	rows, err := q.db.Query(ctx, listUnreadFeedback, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Feedback{}
	for rows.Next() {
		var i Feedback
		if err := rows.Scan(
			&i.ID,
			&i.UserEmail,
			&i.UserRole,
			&i.Category,
			&i.Rating,
			&i.Message,
			&i.PageUrl,
			&i.UserAgent,
			&i.Ip,
			&i.IsRead,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllFeedbackRead = `-- name: MarkAllFeedbackRead :exec
UPDATE feedback SET is_read = TRUE WHERE is_read = FALSE
`

func (q *Queries) MarkAllFeedbackRead(ctx context.Context) error {
	_, err := q.db.Exec(ctx, markAllFeedbackRead)
	return err
}

const markFeedbackRead = `-- name: MarkFeedbackRead :exec
UPDATE feedback SET is_read = TRUE WHERE id = $1
`

func (q *Queries) MarkFeedbackRead(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markFeedbackRead, id)
	return err
}
