// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: guest_codes.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countGuestCodeLogins = `-- name: CountGuestCodeLogins :one
SELECT COUNT(*) FROM guest_logins WHERE guest_code_id = $1
`

func (q *Queries) CountGuestCodeLogins(ctx context.Context, guestCodeID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countGuestCodeLogins, guestCodeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGuestCode = `-- name: CreateGuestCode :one
INSERT INTO guest_codes (code, product_id, label, max_logins_per_email, expires_at, generated_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, code, product_id, label, max_logins_per_email, expires_at, is_active, generated_by, created_at
`

type CreateGuestCodeParams struct {
	Code              string             `json:"code"`
	ProductID         pgtype.Text        `json:"product_id"`
	Label             pgtype.Text        `json:"label"`
	MaxLoginsPerEmail pgtype.Int4        `json:"max_logins_per_email"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	GeneratedBy       pgtype.UUID        `json:"generated_by"`
}

func (q *Queries) CreateGuestCode(ctx context.Context, arg CreateGuestCodeParams) (GuestCode, error) {
	row := q.db.QueryRow(ctx, createGuestCode,
		arg.Code,
		arg.ProductID,
		arg.Label,
		arg.MaxLoginsPerEmail,
		arg.ExpiresAt,
		arg.GeneratedBy,
	)
	var i GuestCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.ProductID,
		&i.Label,
		&i.MaxLoginsPerEmail,
		&i.ExpiresAt,
		&i.IsActive,
		&i.GeneratedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deactivateGuestCode = `-- name: DeactivateGuestCode :exec
UPDATE guest_codes SET is_active = FALSE WHERE id = $1
`

func (q *Queries) DeactivateGuestCode(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deactivateGuestCode, id)
	return err
}

const getGuestCodeByCode = `-- name: GetGuestCodeByCode :one
SELECT id, code, product_id, label, max_logins_per_email, expires_at, is_active, generated_by, created_at FROM guest_codes WHERE code = $1 AND is_active = TRUE
`

func (q *Queries) GetGuestCodeByCode(ctx context.Context, code string) (GuestCode, error) {
	row := q.db.QueryRow(ctx, getGuestCodeByCode, code)
	var i GuestCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.ProductID,
		&i.Label,
		&i.MaxLoginsPerEmail,
		&i.ExpiresAt,
		&i.IsActive,
		&i.GeneratedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getGuestCodeByID = `-- name: GetGuestCodeByID :one
SELECT id, code, product_id, label, max_logins_per_email, expires_at, is_active, generated_by, created_at FROM guest_codes WHERE id = $1
`

func (q *Queries) GetGuestCodeByID(ctx context.Context, id pgtype.UUID) (GuestCode, error) {
	row := q.db.QueryRow(ctx, getGuestCodeByID, id)
	var i GuestCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.ProductID,
		&i.Label,
		&i.MaxLoginsPerEmail,
		&i.ExpiresAt,
		&i.IsActive,
		&i.GeneratedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getGuestLogin = `-- name: GetGuestLogin :one
SELECT id, guest_code_id, email, login_count, last_login_at, created_at, referral_source FROM guest_logins WHERE guest_code_id = $1 AND email = $2
`

type GetGuestLoginParams struct {
	GuestCodeID pgtype.UUID `json:"guest_code_id"`
	Email       string      `json:"email"`
}

func (q *Queries) GetGuestLogin(ctx context.Context, arg GetGuestLoginParams) (GuestLogin, error) {
	row := q.db.QueryRow(ctx, getGuestLogin, arg.GuestCodeID, arg.Email)
	var i GuestLogin
	err := row.Scan(
		&i.ID,
		&i.GuestCodeID,
		&i.Email,
		&i.LoginCount,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.ReferralSource,
	)
	return i, err
}

const listGuestCodes = `-- name: ListGuestCodes :many
SELECT id, code, product_id, label, max_logins_per_email, expires_at, is_active, generated_by, created_at FROM guest_codes ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListGuestCodesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListGuestCodes(ctx context.Context, arg ListGuestCodesParams) ([]GuestCode, error) {
	rows, err := q.db.Query(ctx, listGuestCodes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GuestCode{}
	for rows.Next() {
		var i GuestCode
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.ProductID,
			&i.Label,
			&i.MaxLoginsPerEmail,
			&i.ExpiresAt,
			&i.IsActive,
			&i.GeneratedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGuestLoginsByCode = `-- name: ListGuestLoginsByCode :many
SELECT id, guest_code_id, email, login_count, last_login_at, created_at, referral_source FROM guest_logins WHERE guest_code_id = $1 ORDER BY last_login_at DESC
`

func (q *Queries) ListGuestLoginsByCode(ctx context.Context, guestCodeID pgtype.UUID) ([]GuestLogin, error) {
	rows, err := q.db.Query(ctx, listGuestLoginsByCode, guestCodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GuestLogin{}
	for rows.Next() {
		var i GuestLogin
		if err := rows.Scan(
			&i.ID,
			&i.GuestCodeID,
			&i.Email,
			&i.LoginCount,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.ReferralSource,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertGuestLogin = `-- name: UpsertGuestLogin :one
INSERT INTO guest_logins (guest_code_id, email, login_count, last_login_at, referral_source)
VALUES ($1, $2, 1, now(), $3)
ON CONFLICT (guest_code_id, email)
DO UPDATE SET login_count = guest_logins.login_count + 1, last_login_at = now(),
  referral_source = CASE WHEN $3 != '' THEN $3 ELSE guest_logins.referral_source END
RETURNING id, guest_code_id, email, login_count, last_login_at, created_at, referral_source
`

type UpsertGuestLoginParams struct {
	GuestCodeID    pgtype.UUID `json:"guest_code_id"`
	Email          string      `json:"email"`
	ReferralSource pgtype.Text `json:"referral_source"`
}

func (q *Queries) UpsertGuestLogin(ctx context.Context, arg UpsertGuestLoginParams) (GuestLogin, error) {
	row := q.db.QueryRow(ctx, upsertGuestLogin, arg.GuestCodeID, arg.Email, arg.ReferralSource)
	var i GuestLogin
	err := row.Scan(
		&i.ID,
		&i.GuestCodeID,
		&i.Email,
		&i.LoginCount,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.ReferralSource,
	)
	return i, err
}
