// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: guest_otps.sql

package repository

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const cleanExpiredOTPs = `-- name: CleanExpiredOTPs :exec
DELETE FROM guest_otps WHERE expires_at < now()
`

func (q *Queries) CleanExpiredOTPs(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanExpiredOTPs)
	return err
}

const countRecentOTPs = `-- name: CountRecentOTPs :one
SELECT COUNT(*) FROM guest_otps
WHERE email = $1
  AND created_at > now() - interval '10 minutes'
`

func (q *Queries) CountRecentOTPs(ctx context.Context, email string) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentOTPs, email)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGuestOTP = `-- name: CreateGuestOTP :one
INSERT INTO guest_otps (email, guest_code_id, otp_code, expires_at, ip)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, guest_code_id, otp_code, expires_at, verified, ip, created_at
`

type CreateGuestOTPParams struct {
	Email       string             `json:"email"`
	GuestCodeID pgtype.UUID        `json:"guest_code_id"`
	OtpCode     string             `json:"otp_code"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	Ip          *netip.Addr        `json:"ip"`
}

func (q *Queries) CreateGuestOTP(ctx context.Context, arg CreateGuestOTPParams) (GuestOtp, error) {
	row := q.db.QueryRow(ctx, createGuestOTP,
		arg.Email,
		arg.GuestCodeID,
		arg.OtpCode,
		arg.ExpiresAt,
		arg.Ip,
	)
	var i GuestOtp
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.GuestCodeID,
		&i.OtpCode,
		&i.ExpiresAt,
		&i.Verified,
		&i.Ip,
		&i.CreatedAt,
	)
	return i, err
}

const getPendingOTP = `-- name: GetPendingOTP :one
SELECT id, email, guest_code_id, otp_code, expires_at, verified, ip, created_at FROM guest_otps
WHERE email = $1
  AND guest_code_id = $2
  AND otp_code = $3
  AND verified = FALSE
  AND expires_at > now()
ORDER BY created_at DESC
LIMIT 1
`

type GetPendingOTPParams struct {
	Email       string      `json:"email"`
	GuestCodeID pgtype.UUID `json:"guest_code_id"`
	OtpCode     string      `json:"otp_code"`
}

func (q *Queries) GetPendingOTP(ctx context.Context, arg GetPendingOTPParams) (GuestOtp, error) {
	row := q.db.QueryRow(ctx, getPendingOTP, arg.Email, arg.GuestCodeID, arg.OtpCode)
	var i GuestOtp
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.GuestCodeID,
		&i.OtpCode,
		&i.ExpiresAt,
		&i.Verified,
		&i.Ip,
		&i.CreatedAt,
	)
	return i, err
}

const markOTPVerified = `-- name: MarkOTPVerified :exec
UPDATE guest_otps SET verified = TRUE WHERE id = $1
`

func (q *Queries) MarkOTPVerified(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markOTPVerified, id)
	return err
}
