// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: guest_codes.sql

package repository

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const countGuestCodeLogins = `-- name: CountGuestCodeLogins :one
SELECT COUNT(*) FROM guest_logins WHERE guest_code_id = $1
`

func (q *Queries) CountGuestCodeLogins(ctx context.Context, guestCodeID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countGuestCodeLogins, guestCodeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGuestCode = `-- name: CreateGuestCode :one
INSERT INTO guest_codes (code, product_id, label, max_logins_per_email, expires_at, generated_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, code, product_id, label, max_logins_per_email, expires_at, is_active, generated_by, created_at
`

type CreateGuestCodeParams struct {
	Code              string             `json:"code"`
	ProductID         pgtype.Text        `json:"product_id"`
	Label             pgtype.Text        `json:"label"`
	MaxLoginsPerEmail pgtype.Int4        `json:"max_logins_per_email"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	GeneratedBy       pgtype.UUID        `json:"generated_by"`
}

func (q *Queries) CreateGuestCode(ctx context.Context, arg CreateGuestCodeParams) (GuestCode, error) {
	row := q.db.QueryRow(ctx, createGuestCode,
		arg.Code,
		arg.ProductID,
		arg.Label,
		arg.MaxLoginsPerEmail,
		arg.ExpiresAt,
		arg.GeneratedBy,
	)
	var i GuestCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.ProductID,
		&i.Label,
		&i.MaxLoginsPerEmail,
		&i.ExpiresAt,
		&i.IsActive,
		&i.GeneratedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deactivateGuestCode = `-- name: DeactivateGuestCode :exec
UPDATE guest_codes SET is_active = FALSE WHERE id = $1
`

func (q *Queries) DeactivateGuestCode(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deactivateGuestCode, id)
	return err
}

const deleteGuestCode = `-- name: DeleteGuestCode :exec
DELETE FROM guest_codes WHERE id = $1
`

func (q *Queries) DeleteGuestCode(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteGuestCode, id)
	return err
}

const getGuestCodeByCode = `-- name: GetGuestCodeByCode :one
SELECT id, code, product_id, label, max_logins_per_email, expires_at, is_active, generated_by, created_at FROM guest_codes WHERE UPPER(code) = UPPER($1) AND is_active = TRUE
`

func (q *Queries) GetGuestCodeByCode(ctx context.Context, upper interface{}) (GuestCode, error) {
	row := q.db.QueryRow(ctx, getGuestCodeByCode, upper)
	var i GuestCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.ProductID,
		&i.Label,
		&i.MaxLoginsPerEmail,
		&i.ExpiresAt,
		&i.IsActive,
		&i.GeneratedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getGuestCodeByID = `-- name: GetGuestCodeByID :one
SELECT id, code, product_id, label, max_logins_per_email, expires_at, is_active, generated_by, created_at FROM guest_codes WHERE id = $1
`

func (q *Queries) GetGuestCodeByID(ctx context.Context, id pgtype.UUID) (GuestCode, error) {
	row := q.db.QueryRow(ctx, getGuestCodeByID, id)
	var i GuestCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.ProductID,
		&i.Label,
		&i.MaxLoginsPerEmail,
		&i.ExpiresAt,
		&i.IsActive,
		&i.GeneratedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getGuestLogin = `-- name: GetGuestLogin :one
SELECT id, guest_code_id, email, login_count, last_login_at, created_at, referral_source, ip_address FROM guest_logins WHERE guest_code_id = $1 AND email = $2
`

type GetGuestLoginParams struct {
	GuestCodeID pgtype.UUID `json:"guest_code_id"`
	Email       string      `json:"email"`
}

func (q *Queries) GetGuestLogin(ctx context.Context, arg GetGuestLoginParams) (GuestLogin, error) {
	row := q.db.QueryRow(ctx, getGuestLogin, arg.GuestCodeID, arg.Email)
	var i GuestLogin
	err := row.Scan(
		&i.ID,
		&i.GuestCodeID,
		&i.Email,
		&i.LoginCount,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.ReferralSource,
		&i.IpAddress,
	)
	return i, err
}

const listAllAudience = `-- name: ListAllAudience :many
SELECT
  gl.email,
  'guest'::text AS user_type,
  gc.code AS guest_code,
  COALESCE(gl.referral_source, '') AS referral_source,
  COALESCE(gl.ip_address::text, '') AS ip_address,
  gl.login_count::bigint AS total_logins,
  0::bigint AS amount_paid,
  gl.last_login_at AS last_active,
  gl.created_at
FROM guest_logins gl
JOIN guest_codes gc ON gc.id = gl.guest_code_id
UNION ALL
SELECT
  u.email,
  u.role::text AS user_type,
  ''::text AS guest_code,
  ''::text AS referral_source,
  COALESCE((SELECT s3.ip_at_login::text FROM sessions s3 WHERE s3.user_id = u.id AND s3.ip_at_login IS NOT NULL ORDER BY s3.created_at DESC LIMIT 1), '') AS ip_address,
  COUNT(s2.id)::bigint AS total_logins,
  COALESCE(SUM(sub.amount_paid_idr), 0)::bigint AS amount_paid,
  COALESCE(MAX(s2.created_at), u.created_at) AS last_active,
  u.created_at
FROM users u
LEFT JOIN sessions s2 ON s2.user_id = u.id
LEFT JOIN subscriptions sub ON sub.user_id = u.id AND sub.status = 'active'
GROUP BY u.id, u.email, u.role, u.created_at
ORDER BY last_active DESC
LIMIT $1 OFFSET $2
`

type ListAllAudienceParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListAllAudienceRow struct {
	Email          string             `json:"email"`
	UserType       string             `json:"user_type"`
	GuestCode      string             `json:"guest_code"`
	ReferralSource string             `json:"referral_source"`
	IpAddress      interface{}        `json:"ip_address"`
	TotalLogins    int64              `json:"total_logins"`
	AmountPaid     int64              `json:"amount_paid"`
	LastActive     pgtype.Timestamptz `json:"last_active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListAllAudience(ctx context.Context, arg ListAllAudienceParams) ([]ListAllAudienceRow, error) {
	rows, err := q.db.Query(ctx, listAllAudience, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllAudienceRow{}
	for rows.Next() {
		var i ListAllAudienceRow
		if err := rows.Scan(
			&i.Email,
			&i.UserType,
			&i.GuestCode,
			&i.ReferralSource,
			&i.IpAddress,
			&i.TotalLogins,
			&i.AmountPaid,
			&i.LastActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGuestCodes = `-- name: ListGuestCodes :many
SELECT id, code, product_id, label, max_logins_per_email, expires_at, is_active, generated_by, created_at FROM guest_codes ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListGuestCodesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListGuestCodes(ctx context.Context, arg ListGuestCodesParams) ([]GuestCode, error) {
	rows, err := q.db.Query(ctx, listGuestCodes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GuestCode{}
	for rows.Next() {
		var i GuestCode
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.ProductID,
			&i.Label,
			&i.MaxLoginsPerEmail,
			&i.ExpiresAt,
			&i.IsActive,
			&i.GeneratedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGuestLoginsByCode = `-- name: ListGuestLoginsByCode :many
SELECT id, guest_code_id, email, login_count, last_login_at, created_at, referral_source, ip_address FROM guest_logins WHERE guest_code_id = $1 ORDER BY last_login_at DESC
`

func (q *Queries) ListGuestLoginsByCode(ctx context.Context, guestCodeID pgtype.UUID) ([]GuestLogin, error) {
	rows, err := q.db.Query(ctx, listGuestLoginsByCode, guestCodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GuestLogin{}
	for rows.Next() {
		var i GuestLogin
		if err := rows.Scan(
			&i.ID,
			&i.GuestCodeID,
			&i.Email,
			&i.LoginCount,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.ReferralSource,
			&i.IpAddress,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumGuestCodeLogins = `-- name: SumGuestCodeLogins :one
SELECT COALESCE(SUM(login_count), 0)::bigint FROM guest_logins WHERE guest_code_id = $1
`

func (q *Queries) SumGuestCodeLogins(ctx context.Context, guestCodeID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, sumGuestCodeLogins, guestCodeID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const upsertGuestLogin = `-- name: UpsertGuestLogin :one
INSERT INTO guest_logins (guest_code_id, email, login_count, last_login_at, referral_source, ip_address)
VALUES ($1, $2, 1, now(), $3, $4)
ON CONFLICT (guest_code_id, email)
DO UPDATE SET login_count = guest_logins.login_count + 1, last_login_at = now(),
  referral_source = CASE WHEN $3 != '' THEN $3 ELSE guest_logins.referral_source END,
  ip_address = COALESCE($4, guest_logins.ip_address)
RETURNING id, guest_code_id, email, login_count, last_login_at, created_at, referral_source, ip_address
`

type UpsertGuestLoginParams struct {
	GuestCodeID    pgtype.UUID `json:"guest_code_id"`
	Email          string      `json:"email"`
	ReferralSource pgtype.Text `json:"referral_source"`
	IpAddress      *netip.Addr `json:"ip_address"`
}

func (q *Queries) UpsertGuestLogin(ctx context.Context, arg UpsertGuestLoginParams) (GuestLogin, error) {
	row := q.db.QueryRow(ctx, upsertGuestLogin,
		arg.GuestCodeID,
		arg.Email,
		arg.ReferralSource,
		arg.IpAddress,
	)
	var i GuestLogin
	err := row.Scan(
		&i.ID,
		&i.GuestCodeID,
		&i.Email,
		&i.LoginCount,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.ReferralSource,
		&i.IpAddress,
	)
	return i, err
}
