// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type AccessLog struct {
	ID         int64              `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	SessionID  pgtype.UUID        `json:"session_id"`
	Ip         *netip.Addr        `json:"ip"`
	Endpoint   pgtype.Text        `json:"endpoint"`
	Method     pgtype.Text        `json:"method"`
	StatusCode pgtype.Int4        `json:"status_code"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type AdminAuditLog struct {
	ID         int64              `json:"id"`
	AdminEmail string             `json:"admin_email"`
	Action     string             `json:"action"`
	Resource   string             `json:"resource"`
	ResourceID pgtype.Text        `json:"resource_id"`
	Detail     pgtype.Text        `json:"detail"`
	Ip         *netip.Addr        `json:"ip"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type AnomalyLog struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Event      string             `json:"event"`
	ScoreDelta int32              `json:"score_delta"`
	Detail     []byte             `json:"detail"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type GuestCode struct {
	ID                pgtype.UUID        `json:"id"`
	Code              string             `json:"code"`
	ProductID         pgtype.Text        `json:"product_id"`
	Label             pgtype.Text        `json:"label"`
	MaxLoginsPerEmail pgtype.Int4        `json:"max_logins_per_email"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	IsActive          pgtype.Bool        `json:"is_active"`
	GeneratedBy       pgtype.UUID        `json:"generated_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type GuestLogin struct {
	ID          pgtype.UUID        `json:"id"`
	GuestCodeID pgtype.UUID        `json:"guest_code_id"`
	Email       string             `json:"email"`
	LoginCount  pgtype.Int4        `json:"login_count"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type PricingPlan struct {
	ID           pgtype.UUID        `json:"id"`
	ProductID    pgtype.Text        `json:"product_id"`
	Segment      string             `json:"segment"`
	Duration     string             `json:"duration"`
	DurationDays int32              `json:"duration_days"`
	PriceIdr     int32              `json:"price_idr"`
	Label        pgtype.Text        `json:"label"`
	IsActive     pgtype.Bool        `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Product struct {
	ID          string             `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	IsActive    pgtype.Bool        `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Session struct {
	ID                pgtype.UUID        `json:"id"`
	UserID            pgtype.UUID        `json:"user_id"`
	GuestCodeID       pgtype.UUID        `json:"guest_code_id"`
	GuestEmail        pgtype.Text        `json:"guest_email"`
	RefreshTokenHash  string             `json:"refresh_token_hash"`
	DeviceFingerprint pgtype.Text        `json:"device_fingerprint"`
	IpAtLogin         *netip.Addr        `json:"ip_at_login"`
	UserAgent         pgtype.Text        `json:"user_agent"`
	CountryCode       pgtype.Text        `json:"country_code"`
	IsActive          pgtype.Bool        `json:"is_active"`
	RevokedAt         pgtype.Timestamptz `json:"revoked_at"`
	RevokeReason      pgtype.Text        `json:"revoke_reason"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type Subscription struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	ProductID       pgtype.Text        `json:"product_id"`
	PlanID          pgtype.UUID        `json:"plan_id"`
	Segment         string             `json:"segment"`
	XenditInvoiceID pgtype.Text        `json:"xendit_invoice_id"`
	XenditPaymentID pgtype.Text        `json:"xendit_payment_id"`
	AmountPaidIdr   pgtype.Int4        `json:"amount_paid_idr"`
	Status          pgtype.Text        `json:"status"`
	PaidAt          pgtype.Timestamptz `json:"paid_at"`
	StartsAt        pgtype.Timestamptz `json:"starts_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type SystemConfig struct {
	Key         string             `json:"key"`
	Value       string             `json:"value"`
	Description pgtype.Text        `json:"description"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy   pgtype.UUID        `json:"updated_by"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	Name         pgtype.Text        `json:"name"`
	PasswordHash string             `json:"password_hash"`
	Role         pgtype.Text        `json:"role"`
	IsActive     pgtype.Bool        `json:"is_active"`
	AnomalyScore pgtype.Int4        `json:"anomaly_score"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
