// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pricing_plans.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPricingPlan = `-- name: CreatePricingPlan :one
INSERT INTO pricing_plans (product_id, segment, duration, duration_days, price_idr, label, is_active)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, product_id, segment, duration, duration_days, price_idr, label, is_active, created_at
`

type CreatePricingPlanParams struct {
	ProductID    pgtype.Text `json:"product_id"`
	Segment      string      `json:"segment"`
	Duration     string      `json:"duration"`
	DurationDays int32       `json:"duration_days"`
	PriceIdr     int32       `json:"price_idr"`
	Label        pgtype.Text `json:"label"`
	IsActive     pgtype.Bool `json:"is_active"`
}

func (q *Queries) CreatePricingPlan(ctx context.Context, arg CreatePricingPlanParams) (PricingPlan, error) {
	row := q.db.QueryRow(ctx, createPricingPlan,
		arg.ProductID,
		arg.Segment,
		arg.Duration,
		arg.DurationDays,
		arg.PriceIdr,
		arg.Label,
		arg.IsActive,
	)
	var i PricingPlan
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Segment,
		&i.Duration,
		&i.DurationDays,
		&i.PriceIdr,
		&i.Label,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getPricingPlan = `-- name: GetPricingPlan :one
SELECT id, product_id, segment, duration, duration_days, price_idr, label, is_active, created_at FROM pricing_plans WHERE id = $1
`

func (q *Queries) GetPricingPlan(ctx context.Context, id pgtype.UUID) (PricingPlan, error) {
	row := q.db.QueryRow(ctx, getPricingPlan, id)
	var i PricingPlan
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Segment,
		&i.Duration,
		&i.DurationDays,
		&i.PriceIdr,
		&i.Label,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listAllPricingPlans = `-- name: ListAllPricingPlans :many
SELECT id, product_id, segment, duration, duration_days, price_idr, label, is_active, created_at FROM pricing_plans
ORDER BY segment, price_idr ASC
`

func (q *Queries) ListAllPricingPlans(ctx context.Context) ([]PricingPlan, error) {
	rows, err := q.db.Query(ctx, listAllPricingPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PricingPlan{}
	for rows.Next() {
		var i PricingPlan
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Segment,
			&i.Duration,
			&i.DurationDays,
			&i.PriceIdr,
			&i.Label,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPricingPlansByProduct = `-- name: ListPricingPlansByProduct :many
SELECT id, product_id, segment, duration, duration_days, price_idr, label, is_active, created_at FROM pricing_plans
WHERE product_id = $1 AND is_active = TRUE
ORDER BY price_idr ASC
`

func (q *Queries) ListPricingPlansByProduct(ctx context.Context, productID pgtype.Text) ([]PricingPlan, error) {
	rows, err := q.db.Query(ctx, listPricingPlansByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PricingPlan{}
	for rows.Next() {
		var i PricingPlan
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Segment,
			&i.Duration,
			&i.DurationDays,
			&i.PriceIdr,
			&i.Label,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const togglePricingPlanActive = `-- name: TogglePricingPlanActive :exec
UPDATE pricing_plans
SET is_active = NOT is_active
WHERE id = $1
`

func (q *Queries) TogglePricingPlanActive(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, togglePricingPlanActive, id)
	return err
}

const updatePricingPlan = `-- name: UpdatePricingPlan :exec
UPDATE pricing_plans
SET price_idr = $2, label = $3, is_active = $4
WHERE id = $1
`

type UpdatePricingPlanParams struct {
	ID       pgtype.UUID `json:"id"`
	PriceIdr int32       `json:"price_idr"`
	Label    pgtype.Text `json:"label"`
	IsActive pgtype.Bool `json:"is_active"`
}

func (q *Queries) UpdatePricingPlan(ctx context.Context, arg UpdatePricingPlanParams) error {
	_, err := q.db.Exec(ctx, updatePricingPlan,
		arg.ID,
		arg.PriceIdr,
		arg.Label,
		arg.IsActive,
	)
	return err
}

const updatePricingPlanPrice = `-- name: UpdatePricingPlanPrice :exec
UPDATE pricing_plans
SET price_idr = $2
WHERE id = $1
`

type UpdatePricingPlanPriceParams struct {
	ID       pgtype.UUID `json:"id"`
	PriceIdr int32       `json:"price_idr"`
}

func (q *Queries) UpdatePricingPlanPrice(ctx context.Context, arg UpdatePricingPlanPriceParams) error {
	_, err := q.db.Exec(ctx, updatePricingPlanPrice, arg.ID, arg.PriceIdr)
	return err
}
