// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ActivateSubscriptionByInvoice(ctx context.Context, arg ActivateSubscriptionByInvoiceParams) error
	CleanExpiredSessions(ctx context.Context) error
	CountActiveGuestSessions(ctx context.Context) (int64, error)
	CountActiveSubscribers(ctx context.Context) (int64, error)
	CountActiveSubscriptions(ctx context.Context) (int64, error)
	CountAllSubscriptions(ctx context.Context) (int64, error)
	CountGuestCodeLogins(ctx context.Context, guestCodeID pgtype.UUID) (int64, error)
	CountSearchUsers(ctx context.Context, dollar_1 pgtype.Text) (int64, error)
	CountSearchUsersByRole(ctx context.Context, arg CountSearchUsersByRoleParams) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateAccessLog(ctx context.Context, arg CreateAccessLogParams) error
	CreateAnomalyLog(ctx context.Context, arg CreateAnomalyLogParams) (AnomalyLog, error)
	CreateGuestCode(ctx context.Context, arg CreateGuestCodeParams) (GuestCode, error)
	CreatePricingPlan(ctx context.Context, arg CreatePricingPlanParams) (PricingPlan, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeactivateGuestCode(ctx context.Context, id pgtype.UUID) error
	GetActiveSessionByUserID(ctx context.Context, userID pgtype.UUID) (Session, error)
	GetActiveSubscription(ctx context.Context, arg GetActiveSubscriptionParams) (Subscription, error)
	GetConfig(ctx context.Context, key string) (SystemConfig, error)
	GetGuestCodeByCode(ctx context.Context, code string) (GuestCode, error)
	GetGuestCodeByID(ctx context.Context, id pgtype.UUID) (GuestCode, error)
	GetGuestLogin(ctx context.Context, arg GetGuestLoginParams) (GuestLogin, error)
	GetMonthlyRevenue(ctx context.Context) ([]GetMonthlyRevenueRow, error)
	GetMonthlySubscriptionCount(ctx context.Context) ([]GetMonthlySubscriptionCountRow, error)
	GetPricingPlan(ctx context.Context, id pgtype.UUID) (PricingPlan, error)
	GetProduct(ctx context.Context, id string) (Product, error)
	GetRevenueBySegment(ctx context.Context) ([]GetRevenueBySegmentRow, error)
	GetSessionByID(ctx context.Context, id pgtype.UUID) (Session, error)
	GetSessionByRefreshToken(ctx context.Context, refreshTokenHash string) (Session, error)
	GetSubscriptionByID(ctx context.Context, id pgtype.UUID) (Subscription, error)
	GetTotalRevenue(ctx context.Context) (int64, error)
	GetUserAnomalyScore(ctx context.Context, userID pgtype.UUID) (int64, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	ListAllPricingPlans(ctx context.Context) ([]PricingPlan, error)
	ListAllSubscriptions(ctx context.Context, arg ListAllSubscriptionsParams) ([]ListAllSubscriptionsRow, error)
	ListAnomalyLogsByUser(ctx context.Context, arg ListAnomalyLogsByUserParams) ([]AnomalyLog, error)
	ListConfigs(ctx context.Context) ([]SystemConfig, error)
	ListExpiringSubscriptions(ctx context.Context) ([]ListExpiringSubscriptionsRow, error)
	ListFlaggedUsers(ctx context.Context, arg ListFlaggedUsersParams) ([]ListFlaggedUsersRow, error)
	ListGuestCodes(ctx context.Context, arg ListGuestCodesParams) ([]GuestCode, error)
	ListGuestLoginsByCode(ctx context.Context, guestCodeID pgtype.UUID) ([]GuestLogin, error)
	ListPricingPlansByProduct(ctx context.Context, productID pgtype.Text) ([]PricingPlan, error)
	ListProducts(ctx context.Context) ([]Product, error)
	ListRecentAnomalies(ctx context.Context, arg ListRecentAnomaliesParams) ([]ListRecentAnomaliesRow, error)
	ListSessionsByUser(ctx context.Context, userID pgtype.UUID) ([]Session, error)
	ListSubscriptionsByStatus(ctx context.Context, arg ListSubscriptionsByStatusParams) ([]ListSubscriptionsByStatusRow, error)
	ListUserSubscriptions(ctx context.Context, userID pgtype.UUID) ([]Subscription, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	RevokeAllUserSessions(ctx context.Context, userID pgtype.UUID) error
	RevokeSession(ctx context.Context, arg RevokeSessionParams) error
	SearchUsers(ctx context.Context, arg SearchUsersParams) ([]User, error)
	SearchUsersByRole(ctx context.Context, arg SearchUsersByRoleParams) ([]User, error)
	SetUserActive(ctx context.Context, arg SetUserActiveParams) error
	SetXenditInvoiceID(ctx context.Context, arg SetXenditInvoiceIDParams) error
	TogglePricingPlanActive(ctx context.Context, id pgtype.UUID) error
	UpdateConfig(ctx context.Context, arg UpdateConfigParams) error
	UpdatePricingPlan(ctx context.Context, arg UpdatePricingPlanParams) error
	UpdatePricingPlanPrice(ctx context.Context, arg UpdatePricingPlanPriceParams) error
	UpdateSubscriptionStatus(ctx context.Context, arg UpdateSubscriptionStatusParams) error
	UpdateUserAnomalyScore(ctx context.Context, arg UpdateUserAnomalyScoreParams) error
	UpsertConfig(ctx context.Context, arg UpsertConfigParams) error
	UpsertGuestLogin(ctx context.Context, arg UpsertGuestLoginParams) (GuestLogin, error)
}

var _ Querier = (*Queries)(nil)
