// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package repository

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const cleanExpiredSessions = `-- name: CleanExpiredSessions :exec
UPDATE sessions
SET is_active = FALSE, revoked_at = now(), revoke_reason = 'expired'
WHERE is_active = TRUE AND expires_at < now()
`

func (q *Queries) CleanExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanExpiredSessions)
	return err
}

const countActiveGuestSessions = `-- name: CountActiveGuestSessions :one
SELECT COUNT(*) FROM sessions
WHERE guest_code_id IS NOT NULL AND is_active = TRUE AND expires_at > now()
`

func (q *Queries) CountActiveGuestSessions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveGuestSessions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
  user_id, guest_code_id, guest_email,
  refresh_token_hash, device_fingerprint,
  ip_at_login, user_agent, country_code, expires_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, guest_code_id, guest_email, refresh_token_hash, device_fingerprint, ip_at_login, user_agent, country_code, is_active, revoked_at, revoke_reason, expires_at, created_at
`

type CreateSessionParams struct {
	UserID            pgtype.UUID        `json:"user_id"`
	GuestCodeID       pgtype.UUID        `json:"guest_code_id"`
	GuestEmail        pgtype.Text        `json:"guest_email"`
	RefreshTokenHash  string             `json:"refresh_token_hash"`
	DeviceFingerprint pgtype.Text        `json:"device_fingerprint"`
	IpAtLogin         *netip.Addr        `json:"ip_at_login"`
	UserAgent         pgtype.Text        `json:"user_agent"`
	CountryCode       pgtype.Text        `json:"country_code"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.GuestCodeID,
		arg.GuestEmail,
		arg.RefreshTokenHash,
		arg.DeviceFingerprint,
		arg.IpAtLogin,
		arg.UserAgent,
		arg.CountryCode,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GuestCodeID,
		&i.GuestEmail,
		&i.RefreshTokenHash,
		&i.DeviceFingerprint,
		&i.IpAtLogin,
		&i.UserAgent,
		&i.CountryCode,
		&i.IsActive,
		&i.RevokedAt,
		&i.RevokeReason,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveSessionByUserID = `-- name: GetActiveSessionByUserID :one
SELECT id, user_id, guest_code_id, guest_email, refresh_token_hash, device_fingerprint, ip_at_login, user_agent, country_code, is_active, revoked_at, revoke_reason, expires_at, created_at FROM sessions WHERE user_id = $1 AND is_active = TRUE LIMIT 1
`

func (q *Queries) GetActiveSessionByUserID(ctx context.Context, userID pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getActiveSessionByUserID, userID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GuestCodeID,
		&i.GuestEmail,
		&i.RefreshTokenHash,
		&i.DeviceFingerprint,
		&i.IpAtLogin,
		&i.UserAgent,
		&i.CountryCode,
		&i.IsActive,
		&i.RevokedAt,
		&i.RevokeReason,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, user_id, guest_code_id, guest_email, refresh_token_hash, device_fingerprint, ip_at_login, user_agent, country_code, is_active, revoked_at, revoke_reason, expires_at, created_at FROM sessions WHERE id = $1 AND is_active = TRUE
`

func (q *Queries) GetSessionByID(ctx context.Context, id pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GuestCodeID,
		&i.GuestEmail,
		&i.RefreshTokenHash,
		&i.DeviceFingerprint,
		&i.IpAtLogin,
		&i.UserAgent,
		&i.CountryCode,
		&i.IsActive,
		&i.RevokedAt,
		&i.RevokeReason,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByRefreshToken = `-- name: GetSessionByRefreshToken :one
SELECT id, user_id, guest_code_id, guest_email, refresh_token_hash, device_fingerprint, ip_at_login, user_agent, country_code, is_active, revoked_at, revoke_reason, expires_at, created_at FROM sessions WHERE refresh_token_hash = $1 AND is_active = TRUE
`

func (q *Queries) GetSessionByRefreshToken(ctx context.Context, refreshTokenHash string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByRefreshToken, refreshTokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GuestCodeID,
		&i.GuestEmail,
		&i.RefreshTokenHash,
		&i.DeviceFingerprint,
		&i.IpAtLogin,
		&i.UserAgent,
		&i.CountryCode,
		&i.IsActive,
		&i.RevokedAt,
		&i.RevokeReason,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const listSessionsByUser = `-- name: ListSessionsByUser :many
SELECT id, user_id, guest_code_id, guest_email, refresh_token_hash, device_fingerprint, ip_at_login, user_agent, country_code, is_active, revoked_at, revoke_reason, expires_at, created_at FROM sessions WHERE user_id = $1 ORDER BY created_at DESC LIMIT 20
`

func (q *Queries) ListSessionsByUser(ctx context.Context, userID pgtype.UUID) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GuestCodeID,
			&i.GuestEmail,
			&i.RefreshTokenHash,
			&i.DeviceFingerprint,
			&i.IpAtLogin,
			&i.UserAgent,
			&i.CountryCode,
			&i.IsActive,
			&i.RevokedAt,
			&i.RevokeReason,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :exec
UPDATE sessions
SET is_active = FALSE, revoked_at = now(), revoke_reason = 'new_login'
WHERE user_id = $1 AND is_active = TRUE
`

func (q *Queries) RevokeAllUserSessions(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserSessions, userID)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions
SET is_active = FALSE, revoked_at = now(), revoke_reason = $2
WHERE id = $1
`

type RevokeSessionParams struct {
	ID           pgtype.UUID `json:"id"`
	RevokeReason pgtype.Text `json:"revoke_reason"`
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) error {
	_, err := q.db.Exec(ctx, revokeSession, arg.ID, arg.RevokeReason)
	return err
}
