// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscriptions.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateSubscriptionByInvoice = `-- name: ActivateSubscriptionByInvoice :exec
UPDATE subscriptions
SET status = 'active', paid_at = now(), starts_at = now(), xendit_payment_id = $2
WHERE xendit_invoice_id = $1
`

type ActivateSubscriptionByInvoiceParams struct {
	XenditInvoiceID pgtype.Text `json:"xendit_invoice_id"`
	XenditPaymentID pgtype.Text `json:"xendit_payment_id"`
}

func (q *Queries) ActivateSubscriptionByInvoice(ctx context.Context, arg ActivateSubscriptionByInvoiceParams) error {
	_, err := q.db.Exec(ctx, activateSubscriptionByInvoice, arg.XenditInvoiceID, arg.XenditPaymentID)
	return err
}

const activateSubscriptionFull = `-- name: ActivateSubscriptionFull :exec
UPDATE subscriptions
SET status = 'active', paid_at = now(), starts_at = now(),
    expires_at = now() + ($2 || ' days')::interval,
    xendit_invoice_id = $3
WHERE id = $1
`

type ActivateSubscriptionFullParams struct {
	ID              pgtype.UUID `json:"id"`
	Column2         pgtype.Text `json:"column_2"`
	XenditInvoiceID pgtype.Text `json:"xendit_invoice_id"`
}

func (q *Queries) ActivateSubscriptionFull(ctx context.Context, arg ActivateSubscriptionFullParams) error {
	_, err := q.db.Exec(ctx, activateSubscriptionFull, arg.ID, arg.Column2, arg.XenditInvoiceID)
	return err
}

const countActiveSubscriptions = `-- name: CountActiveSubscriptions :one
SELECT COUNT(*) FROM subscriptions WHERE status = 'active' AND expires_at > now()
`

func (q *Queries) CountActiveSubscriptions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveSubscriptions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAllSubscriptions = `-- name: CountAllSubscriptions :one
SELECT COUNT(*) FROM subscriptions
`

func (q *Queries) CountAllSubscriptions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllSubscriptions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (
  user_id, product_id, plan_id, segment,
  xendit_invoice_id, amount_paid_idr, status, expires_at, utm_source
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, product_id, plan_id, segment, xendit_invoice_id, xendit_payment_id, amount_paid_idr, status, paid_at, starts_at, expires_at, created_at, utm_source
`

type CreateSubscriptionParams struct {
	UserID          pgtype.UUID        `json:"user_id"`
	ProductID       pgtype.Text        `json:"product_id"`
	PlanID          pgtype.UUID        `json:"plan_id"`
	Segment         string             `json:"segment"`
	XenditInvoiceID pgtype.Text        `json:"xendit_invoice_id"`
	AmountPaidIdr   pgtype.Int4        `json:"amount_paid_idr"`
	Status          pgtype.Text        `json:"status"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	UtmSource       pgtype.Text        `json:"utm_source"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscription,
		arg.UserID,
		arg.ProductID,
		arg.PlanID,
		arg.Segment,
		arg.XenditInvoiceID,
		arg.AmountPaidIdr,
		arg.Status,
		arg.ExpiresAt,
		arg.UtmSource,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.PlanID,
		&i.Segment,
		&i.XenditInvoiceID,
		&i.XenditPaymentID,
		&i.AmountPaidIdr,
		&i.Status,
		&i.PaidAt,
		&i.StartsAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UtmSource,
	)
	return i, err
}

const getActiveSubscription = `-- name: GetActiveSubscription :one
SELECT id, user_id, product_id, plan_id, segment, xendit_invoice_id, xendit_payment_id, amount_paid_idr, status, paid_at, starts_at, expires_at, created_at, utm_source FROM subscriptions
WHERE user_id = $1 AND product_id = $2 AND status = 'active' AND expires_at > now()
LIMIT 1
`

type GetActiveSubscriptionParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	ProductID pgtype.Text `json:"product_id"`
}

func (q *Queries) GetActiveSubscription(ctx context.Context, arg GetActiveSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, getActiveSubscription, arg.UserID, arg.ProductID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.PlanID,
		&i.Segment,
		&i.XenditInvoiceID,
		&i.XenditPaymentID,
		&i.AmountPaidIdr,
		&i.Status,
		&i.PaidAt,
		&i.StartsAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UtmSource,
	)
	return i, err
}

const getMonthlyRevenue = `-- name: GetMonthlyRevenue :many
SELECT
  TO_CHAR(DATE_TRUNC('month', paid_at), 'YYYY-MM') AS month,
  COALESCE(SUM(amount_paid_idr), 0)::bigint AS revenue
FROM subscriptions
WHERE status = 'active' AND paid_at IS NOT NULL
  AND paid_at >= NOW() - INTERVAL '12 months'
GROUP BY DATE_TRUNC('month', paid_at)
ORDER BY DATE_TRUNC('month', paid_at) ASC
`

type GetMonthlyRevenueRow struct {
	Month   string `json:"month"`
	Revenue int64  `json:"revenue"`
}

func (q *Queries) GetMonthlyRevenue(ctx context.Context) ([]GetMonthlyRevenueRow, error) {
	rows, err := q.db.Query(ctx, getMonthlyRevenue)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMonthlyRevenueRow{}
	for rows.Next() {
		var i GetMonthlyRevenueRow
		if err := rows.Scan(&i.Month, &i.Revenue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMonthlySubscriptionCount = `-- name: GetMonthlySubscriptionCount :many
SELECT
  TO_CHAR(DATE_TRUNC('month', created_at), 'YYYY-MM') AS month,
  COUNT(*) AS total,
  COUNT(*) FILTER (WHERE status = 'active') AS active,
  COUNT(*) FILTER (WHERE status = 'expired') AS expired,
  COUNT(*) FILTER (WHERE status = 'pending') AS pending
FROM subscriptions
WHERE created_at >= NOW() - INTERVAL '12 months'
GROUP BY DATE_TRUNC('month', created_at)
ORDER BY DATE_TRUNC('month', created_at) ASC
`

type GetMonthlySubscriptionCountRow struct {
	Month   string `json:"month"`
	Total   int64  `json:"total"`
	Active  int64  `json:"active"`
	Expired int64  `json:"expired"`
	Pending int64  `json:"pending"`
}

func (q *Queries) GetMonthlySubscriptionCount(ctx context.Context) ([]GetMonthlySubscriptionCountRow, error) {
	rows, err := q.db.Query(ctx, getMonthlySubscriptionCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMonthlySubscriptionCountRow{}
	for rows.Next() {
		var i GetMonthlySubscriptionCountRow
		if err := rows.Scan(
			&i.Month,
			&i.Total,
			&i.Active,
			&i.Expired,
			&i.Pending,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRevenueBySegment = `-- name: GetRevenueBySegment :many
SELECT
  segment,
  COALESCE(SUM(amount_paid_idr), 0)::bigint AS revenue,
  COUNT(*)::bigint AS count
FROM subscriptions
WHERE status = 'active'
GROUP BY segment
ORDER BY revenue DESC
`

type GetRevenueBySegmentRow struct {
	Segment string `json:"segment"`
	Revenue int64  `json:"revenue"`
	Count   int64  `json:"count"`
}

func (q *Queries) GetRevenueBySegment(ctx context.Context) ([]GetRevenueBySegmentRow, error) {
	rows, err := q.db.Query(ctx, getRevenueBySegment)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRevenueBySegmentRow{}
	for rows.Next() {
		var i GetRevenueBySegmentRow
		if err := rows.Scan(&i.Segment, &i.Revenue, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRevenueByUTMSource = `-- name: GetRevenueByUTMSource :many
SELECT
  COALESCE(utm_source, 'direct') AS source,
  COALESCE(SUM(amount_paid_idr), 0)::bigint AS revenue,
  COUNT(*)::bigint AS total_orders,
  COUNT(*) FILTER (WHERE status = 'active')::bigint AS paid_orders
FROM subscriptions
GROUP BY utm_source
ORDER BY revenue DESC
`

type GetRevenueByUTMSourceRow struct {
	Source      string `json:"source"`
	Revenue     int64  `json:"revenue"`
	TotalOrders int64  `json:"total_orders"`
	PaidOrders  int64  `json:"paid_orders"`
}

func (q *Queries) GetRevenueByUTMSource(ctx context.Context) ([]GetRevenueByUTMSourceRow, error) {
	rows, err := q.db.Query(ctx, getRevenueByUTMSource)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRevenueByUTMSourceRow{}
	for rows.Next() {
		var i GetRevenueByUTMSourceRow
		if err := rows.Scan(
			&i.Source,
			&i.Revenue,
			&i.TotalOrders,
			&i.PaidOrders,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubscriptionByID = `-- name: GetSubscriptionByID :one
SELECT id, user_id, product_id, plan_id, segment, xendit_invoice_id, xendit_payment_id, amount_paid_idr, status, paid_at, starts_at, expires_at, created_at, utm_source FROM subscriptions WHERE id = $1
`

func (q *Queries) GetSubscriptionByID(ctx context.Context, id pgtype.UUID) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByID, id)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.PlanID,
		&i.Segment,
		&i.XenditInvoiceID,
		&i.XenditPaymentID,
		&i.AmountPaidIdr,
		&i.Status,
		&i.PaidAt,
		&i.StartsAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UtmSource,
	)
	return i, err
}

const getTotalRevenue = `-- name: GetTotalRevenue :one
SELECT COALESCE(SUM(amount_paid_idr), 0)::bigint FROM subscriptions WHERE status = 'active'
`

func (q *Queries) GetTotalRevenue(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalRevenue)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listAllSubscriptions = `-- name: ListAllSubscriptions :many
SELECT s.id, s.user_id, s.product_id, s.plan_id, s.segment, s.xendit_invoice_id, s.xendit_payment_id, s.amount_paid_idr, s.status, s.paid_at, s.starts_at, s.expires_at, s.created_at, s.utm_source, u.email, u.name FROM subscriptions s
JOIN users u ON u.id = s.user_id
ORDER BY s.created_at DESC LIMIT $1 OFFSET $2
`

type ListAllSubscriptionsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListAllSubscriptionsRow struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	ProductID       pgtype.Text        `json:"product_id"`
	PlanID          pgtype.UUID        `json:"plan_id"`
	Segment         string             `json:"segment"`
	XenditInvoiceID pgtype.Text        `json:"xendit_invoice_id"`
	XenditPaymentID pgtype.Text        `json:"xendit_payment_id"`
	AmountPaidIdr   pgtype.Int4        `json:"amount_paid_idr"`
	Status          pgtype.Text        `json:"status"`
	PaidAt          pgtype.Timestamptz `json:"paid_at"`
	StartsAt        pgtype.Timestamptz `json:"starts_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UtmSource       pgtype.Text        `json:"utm_source"`
	Email           string             `json:"email"`
	Name            pgtype.Text        `json:"name"`
}

func (q *Queries) ListAllSubscriptions(ctx context.Context, arg ListAllSubscriptionsParams) ([]ListAllSubscriptionsRow, error) {
	rows, err := q.db.Query(ctx, listAllSubscriptions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllSubscriptionsRow{}
	for rows.Next() {
		var i ListAllSubscriptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProductID,
			&i.PlanID,
			&i.Segment,
			&i.XenditInvoiceID,
			&i.XenditPaymentID,
			&i.AmountPaidIdr,
			&i.Status,
			&i.PaidAt,
			&i.StartsAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UtmSource,
			&i.Email,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiringSubscriptions = `-- name: ListExpiringSubscriptions :many
SELECT s.id, s.user_id, s.product_id, s.plan_id, s.segment, s.xendit_invoice_id, s.xendit_payment_id, s.amount_paid_idr, s.status, s.paid_at, s.starts_at, s.expires_at, s.created_at, s.utm_source, u.email, u.name FROM subscriptions s
JOIN users u ON u.id = s.user_id
WHERE s.status = 'active' AND s.expires_at BETWEEN now() AND now() + INTERVAL '7 days'
ORDER BY s.expires_at ASC
`

type ListExpiringSubscriptionsRow struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	ProductID       pgtype.Text        `json:"product_id"`
	PlanID          pgtype.UUID        `json:"plan_id"`
	Segment         string             `json:"segment"`
	XenditInvoiceID pgtype.Text        `json:"xendit_invoice_id"`
	XenditPaymentID pgtype.Text        `json:"xendit_payment_id"`
	AmountPaidIdr   pgtype.Int4        `json:"amount_paid_idr"`
	Status          pgtype.Text        `json:"status"`
	PaidAt          pgtype.Timestamptz `json:"paid_at"`
	StartsAt        pgtype.Timestamptz `json:"starts_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UtmSource       pgtype.Text        `json:"utm_source"`
	Email           string             `json:"email"`
	Name            pgtype.Text        `json:"name"`
}

func (q *Queries) ListExpiringSubscriptions(ctx context.Context) ([]ListExpiringSubscriptionsRow, error) {
	rows, err := q.db.Query(ctx, listExpiringSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpiringSubscriptionsRow{}
	for rows.Next() {
		var i ListExpiringSubscriptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProductID,
			&i.PlanID,
			&i.Segment,
			&i.XenditInvoiceID,
			&i.XenditPaymentID,
			&i.AmountPaidIdr,
			&i.Status,
			&i.PaidAt,
			&i.StartsAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UtmSource,
			&i.Email,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptionsByStatus = `-- name: ListSubscriptionsByStatus :many
SELECT s.id, s.user_id, s.product_id, s.plan_id, s.segment, s.xendit_invoice_id, s.xendit_payment_id, s.amount_paid_idr, s.status, s.paid_at, s.starts_at, s.expires_at, s.created_at, s.utm_source, u.email, u.name FROM subscriptions s
JOIN users u ON u.id = s.user_id
WHERE s.status = $1
ORDER BY s.created_at DESC LIMIT $2 OFFSET $3
`

type ListSubscriptionsByStatusParams struct {
	Status pgtype.Text `json:"status"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

type ListSubscriptionsByStatusRow struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	ProductID       pgtype.Text        `json:"product_id"`
	PlanID          pgtype.UUID        `json:"plan_id"`
	Segment         string             `json:"segment"`
	XenditInvoiceID pgtype.Text        `json:"xendit_invoice_id"`
	XenditPaymentID pgtype.Text        `json:"xendit_payment_id"`
	AmountPaidIdr   pgtype.Int4        `json:"amount_paid_idr"`
	Status          pgtype.Text        `json:"status"`
	PaidAt          pgtype.Timestamptz `json:"paid_at"`
	StartsAt        pgtype.Timestamptz `json:"starts_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UtmSource       pgtype.Text        `json:"utm_source"`
	Email           string             `json:"email"`
	Name            pgtype.Text        `json:"name"`
}

func (q *Queries) ListSubscriptionsByStatus(ctx context.Context, arg ListSubscriptionsByStatusParams) ([]ListSubscriptionsByStatusRow, error) {
	rows, err := q.db.Query(ctx, listSubscriptionsByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubscriptionsByStatusRow{}
	for rows.Next() {
		var i ListSubscriptionsByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProductID,
			&i.PlanID,
			&i.Segment,
			&i.XenditInvoiceID,
			&i.XenditPaymentID,
			&i.AmountPaidIdr,
			&i.Status,
			&i.PaidAt,
			&i.StartsAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UtmSource,
			&i.Email,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserSubscriptions = `-- name: ListUserSubscriptions :many
SELECT id, user_id, product_id, plan_id, segment, xendit_invoice_id, xendit_payment_id, amount_paid_idr, status, paid_at, starts_at, expires_at, created_at, utm_source FROM subscriptions WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListUserSubscriptions(ctx context.Context, userID pgtype.UUID) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, listUserSubscriptions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscription{}
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProductID,
			&i.PlanID,
			&i.Segment,
			&i.XenditInvoiceID,
			&i.XenditPaymentID,
			&i.AmountPaidIdr,
			&i.Status,
			&i.PaidAt,
			&i.StartsAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UtmSource,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setXenditInvoiceID = `-- name: SetXenditInvoiceID :exec
UPDATE subscriptions
SET xendit_invoice_id = $2
WHERE id = $1
`

type SetXenditInvoiceIDParams struct {
	ID              pgtype.UUID `json:"id"`
	XenditInvoiceID pgtype.Text `json:"xendit_invoice_id"`
}

func (q *Queries) SetXenditInvoiceID(ctx context.Context, arg SetXenditInvoiceIDParams) error {
	_, err := q.db.Exec(ctx, setXenditInvoiceID, arg.ID, arg.XenditInvoiceID)
	return err
}

const updateSubscriptionStatus = `-- name: UpdateSubscriptionStatus :exec
UPDATE subscriptions
SET status = $2, paid_at = $3, starts_at = $4
WHERE id = $1
`

type UpdateSubscriptionStatusParams struct {
	ID       pgtype.UUID        `json:"id"`
	Status   pgtype.Text        `json:"status"`
	PaidAt   pgtype.Timestamptz `json:"paid_at"`
	StartsAt pgtype.Timestamptz `json:"starts_at"`
}

func (q *Queries) UpdateSubscriptionStatus(ctx context.Context, arg UpdateSubscriptionStatusParams) error {
	_, err := q.db.Exec(ctx, updateSubscriptionStatus,
		arg.ID,
		arg.Status,
		arg.PaidAt,
		arg.StartsAt,
	)
	return err
}
