// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscriptions.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateSubscriptionByInvoice = `-- name: ActivateSubscriptionByInvoice :exec
UPDATE subscriptions
SET status = 'active', paid_at = now(), starts_at = now(), xendit_payment_id = $2
WHERE xendit_invoice_id = $1
`

type ActivateSubscriptionByInvoiceParams struct {
	XenditInvoiceID pgtype.Text `json:"xendit_invoice_id"`
	XenditPaymentID pgtype.Text `json:"xendit_payment_id"`
}

func (q *Queries) ActivateSubscriptionByInvoice(ctx context.Context, arg ActivateSubscriptionByInvoiceParams) error {
	_, err := q.db.Exec(ctx, activateSubscriptionByInvoice, arg.XenditInvoiceID, arg.XenditPaymentID)
	return err
}

const countActiveSubscriptions = `-- name: CountActiveSubscriptions :one
SELECT COUNT(*) FROM subscriptions WHERE status = 'active' AND expires_at > now()
`

func (q *Queries) CountActiveSubscriptions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveSubscriptions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (
  user_id, product_id, plan_id, segment,
  xendit_invoice_id, amount_paid_idr, status, expires_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, product_id, plan_id, segment, xendit_invoice_id, xendit_payment_id, amount_paid_idr, status, paid_at, starts_at, expires_at, created_at
`

type CreateSubscriptionParams struct {
	UserID          pgtype.UUID        `json:"user_id"`
	ProductID       pgtype.Text        `json:"product_id"`
	PlanID          pgtype.UUID        `json:"plan_id"`
	Segment         string             `json:"segment"`
	XenditInvoiceID pgtype.Text        `json:"xendit_invoice_id"`
	AmountPaidIdr   pgtype.Int4        `json:"amount_paid_idr"`
	Status          pgtype.Text        `json:"status"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscription,
		arg.UserID,
		arg.ProductID,
		arg.PlanID,
		arg.Segment,
		arg.XenditInvoiceID,
		arg.AmountPaidIdr,
		arg.Status,
		arg.ExpiresAt,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.PlanID,
		&i.Segment,
		&i.XenditInvoiceID,
		&i.XenditPaymentID,
		&i.AmountPaidIdr,
		&i.Status,
		&i.PaidAt,
		&i.StartsAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveSubscription = `-- name: GetActiveSubscription :one
SELECT id, user_id, product_id, plan_id, segment, xendit_invoice_id, xendit_payment_id, amount_paid_idr, status, paid_at, starts_at, expires_at, created_at FROM subscriptions
WHERE user_id = $1 AND product_id = $2 AND status = 'active' AND expires_at > now()
LIMIT 1
`

type GetActiveSubscriptionParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	ProductID pgtype.Text `json:"product_id"`
}

func (q *Queries) GetActiveSubscription(ctx context.Context, arg GetActiveSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, getActiveSubscription, arg.UserID, arg.ProductID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.PlanID,
		&i.Segment,
		&i.XenditInvoiceID,
		&i.XenditPaymentID,
		&i.AmountPaidIdr,
		&i.Status,
		&i.PaidAt,
		&i.StartsAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSubscriptionByID = `-- name: GetSubscriptionByID :one
SELECT id, user_id, product_id, plan_id, segment, xendit_invoice_id, xendit_payment_id, amount_paid_idr, status, paid_at, starts_at, expires_at, created_at FROM subscriptions WHERE id = $1
`

func (q *Queries) GetSubscriptionByID(ctx context.Context, id pgtype.UUID) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByID, id)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.PlanID,
		&i.Segment,
		&i.XenditInvoiceID,
		&i.XenditPaymentID,
		&i.AmountPaidIdr,
		&i.Status,
		&i.PaidAt,
		&i.StartsAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const listExpiringSubscriptions = `-- name: ListExpiringSubscriptions :many
SELECT s.id, s.user_id, s.product_id, s.plan_id, s.segment, s.xendit_invoice_id, s.xendit_payment_id, s.amount_paid_idr, s.status, s.paid_at, s.starts_at, s.expires_at, s.created_at, u.email, u.name FROM subscriptions s
JOIN users u ON u.id = s.user_id
WHERE s.status = 'active' AND s.expires_at BETWEEN now() AND now() + INTERVAL '7 days'
ORDER BY s.expires_at ASC
`

type ListExpiringSubscriptionsRow struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	ProductID       pgtype.Text        `json:"product_id"`
	PlanID          pgtype.UUID        `json:"plan_id"`
	Segment         string             `json:"segment"`
	XenditInvoiceID pgtype.Text        `json:"xendit_invoice_id"`
	XenditPaymentID pgtype.Text        `json:"xendit_payment_id"`
	AmountPaidIdr   pgtype.Int4        `json:"amount_paid_idr"`
	Status          pgtype.Text        `json:"status"`
	PaidAt          pgtype.Timestamptz `json:"paid_at"`
	StartsAt        pgtype.Timestamptz `json:"starts_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	Email           string             `json:"email"`
	Name            pgtype.Text        `json:"name"`
}

func (q *Queries) ListExpiringSubscriptions(ctx context.Context) ([]ListExpiringSubscriptionsRow, error) {
	rows, err := q.db.Query(ctx, listExpiringSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpiringSubscriptionsRow{}
	for rows.Next() {
		var i ListExpiringSubscriptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProductID,
			&i.PlanID,
			&i.Segment,
			&i.XenditInvoiceID,
			&i.XenditPaymentID,
			&i.AmountPaidIdr,
			&i.Status,
			&i.PaidAt,
			&i.StartsAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.Email,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserSubscriptions = `-- name: ListUserSubscriptions :many
SELECT id, user_id, product_id, plan_id, segment, xendit_invoice_id, xendit_payment_id, amount_paid_idr, status, paid_at, starts_at, expires_at, created_at FROM subscriptions WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListUserSubscriptions(ctx context.Context, userID pgtype.UUID) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, listUserSubscriptions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscription{}
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProductID,
			&i.PlanID,
			&i.Segment,
			&i.XenditInvoiceID,
			&i.XenditPaymentID,
			&i.AmountPaidIdr,
			&i.Status,
			&i.PaidAt,
			&i.StartsAt,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setXenditInvoiceID = `-- name: SetXenditInvoiceID :exec
UPDATE subscriptions
SET xendit_invoice_id = $2
WHERE id = $1
`

type SetXenditInvoiceIDParams struct {
	ID              pgtype.UUID `json:"id"`
	XenditInvoiceID pgtype.Text `json:"xendit_invoice_id"`
}

func (q *Queries) SetXenditInvoiceID(ctx context.Context, arg SetXenditInvoiceIDParams) error {
	_, err := q.db.Exec(ctx, setXenditInvoiceID, arg.ID, arg.XenditInvoiceID)
	return err
}

const updateSubscriptionStatus = `-- name: UpdateSubscriptionStatus :exec
UPDATE subscriptions
SET status = $2, paid_at = $3, starts_at = $4
WHERE id = $1
`

type UpdateSubscriptionStatusParams struct {
	ID       pgtype.UUID        `json:"id"`
	Status   pgtype.Text        `json:"status"`
	PaidAt   pgtype.Timestamptz `json:"paid_at"`
	StartsAt pgtype.Timestamptz `json:"starts_at"`
}

func (q *Queries) UpdateSubscriptionStatus(ctx context.Context, arg UpdateSubscriptionStatusParams) error {
	_, err := q.db.Exec(ctx, updateSubscriptionStatus,
		arg.ID,
		arg.Status,
		arg.PaidAt,
		arg.StartsAt,
	)
	return err
}
