// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: system_config.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getConfig = `-- name: GetConfig :one
SELECT key, value, description, updated_at, updated_by FROM system_config WHERE key = $1
`

func (q *Queries) GetConfig(ctx context.Context, key string) (SystemConfig, error) {
	row := q.db.QueryRow(ctx, getConfig, key)
	var i SystemConfig
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.Description,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const listConfigs = `-- name: ListConfigs :many
SELECT key, value, description, updated_at, updated_by FROM system_config ORDER BY key
`

func (q *Queries) ListConfigs(ctx context.Context) ([]SystemConfig, error) {
	rows, err := q.db.Query(ctx, listConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SystemConfig{}
	for rows.Next() {
		var i SystemConfig
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.Description,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConfig = `-- name: UpdateConfig :exec
UPDATE system_config
SET value = $2, updated_at = now(), updated_by = $3
WHERE key = $1
`

type UpdateConfigParams struct {
	Key       string      `json:"key"`
	Value     string      `json:"value"`
	UpdatedBy pgtype.UUID `json:"updated_by"`
}

func (q *Queries) UpdateConfig(ctx context.Context, arg UpdateConfigParams) error {
	_, err := q.db.Exec(ctx, updateConfig, arg.Key, arg.Value, arg.UpdatedBy)
	return err
}

const upsertConfig = `-- name: UpsertConfig :exec
INSERT INTO system_config (key, value, description)
VALUES ($1, $2, $3)
ON CONFLICT (key) DO UPDATE SET value = $2, updated_at = now()
`

type UpsertConfigParams struct {
	Key         string      `json:"key"`
	Value       string      `json:"value"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) UpsertConfig(ctx context.Context, arg UpsertConfigParams) error {
	_, err := q.db.Exec(ctx, upsertConfig, arg.Key, arg.Value, arg.Description)
	return err
}
