// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveSubscribers = `-- name: CountActiveSubscribers :one
SELECT COUNT(*) FROM users WHERE role = 'subscriber' AND is_active = TRUE
`

func (q *Queries) CountActiveSubscribers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveSubscribers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, name, password_hash, role, is_active)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, name, password_hash, role, is_active, anomaly_score, created_at
`

type CreateUserParams struct {
	Email        string      `json:"email"`
	Name         pgtype.Text `json:"name"`
	PasswordHash string      `json:"password_hash"`
	Role         pgtype.Text `json:"role"`
	IsActive     pgtype.Bool `json:"is_active"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Name,
		arg.PasswordHash,
		arg.Role,
		arg.IsActive,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.AnomalyScore,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, password_hash, role, is_active, anomaly_score, created_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.AnomalyScore,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, password_hash, role, is_active, anomaly_score, created_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.AnomalyScore,
		&i.CreatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, name, password_hash, role, is_active, anomaly_score, created_at FROM users ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.PasswordHash,
			&i.Role,
			&i.IsActive,
			&i.AnomalyScore,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserActive = `-- name: SetUserActive :exec
UPDATE users SET is_active = $1 WHERE id = $2
`

type SetUserActiveParams struct {
	IsActive pgtype.Bool `json:"is_active"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) SetUserActive(ctx context.Context, arg SetUserActiveParams) error {
	_, err := q.db.Exec(ctx, setUserActive, arg.IsActive, arg.ID)
	return err
}

const updateUserAnomalyScore = `-- name: UpdateUserAnomalyScore :exec
UPDATE users SET anomaly_score = $2 WHERE id = $1
`

type UpdateUserAnomalyScoreParams struct {
	ID           pgtype.UUID `json:"id"`
	AnomalyScore pgtype.Int4 `json:"anomaly_score"`
}

func (q *Queries) UpdateUserAnomalyScore(ctx context.Context, arg UpdateUserAnomalyScoreParams) error {
	_, err := q.db.Exec(ctx, updateUserAnomalyScore, arg.ID, arg.AnomalyScore)
	return err
}
