// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveSubscribers = `-- name: CountActiveSubscribers :one
SELECT COUNT(*) FROM users WHERE role = 'subscriber' AND is_active = TRUE
`

func (q *Queries) CountActiveSubscribers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveSubscribers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchUsers = `-- name: CountSearchUsers :one
SELECT COUNT(*) FROM users WHERE email ILIKE '%' || $1 || '%'
`

func (q *Queries) CountSearchUsers(ctx context.Context, dollar_1 pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchUsers, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchUsersByRole = `-- name: CountSearchUsersByRole :one
SELECT COUNT(*) FROM users WHERE email ILIKE '%' || $1 || '%' AND role = $2
`

type CountSearchUsersByRoleParams struct {
	Column1 pgtype.Text `json:"column_1"`
	Role    pgtype.Text `json:"role"`
}

func (q *Queries) CountSearchUsersByRole(ctx context.Context, arg CountSearchUsersByRoleParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchUsersByRole, arg.Column1, arg.Role)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, name, password_hash, role, is_active, utm_source)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, email, name, password_hash, role, is_active, anomaly_score, created_at, utm_source
`

type CreateUserParams struct {
	Email        string      `json:"email"`
	Name         pgtype.Text `json:"name"`
	PasswordHash string      `json:"password_hash"`
	Role         pgtype.Text `json:"role"`
	IsActive     pgtype.Bool `json:"is_active"`
	UtmSource    pgtype.Text `json:"utm_source"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Name,
		arg.PasswordHash,
		arg.Role,
		arg.IsActive,
		arg.UtmSource,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.AnomalyScore,
		&i.CreatedAt,
		&i.UtmSource,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getRegistrationsByUTMSource = `-- name: GetRegistrationsByUTMSource :many
SELECT
  COALESCE(utm_source, 'direct') AS source,
  COUNT(*)::bigint AS total_registrations,
  COUNT(*) FILTER (WHERE is_active = TRUE)::bigint AS active_users
FROM users
WHERE role = 'subscriber'
GROUP BY utm_source
ORDER BY total_registrations DESC
`

type GetRegistrationsByUTMSourceRow struct {
	Source             string `json:"source"`
	TotalRegistrations int64  `json:"total_registrations"`
	ActiveUsers        int64  `json:"active_users"`
}

func (q *Queries) GetRegistrationsByUTMSource(ctx context.Context) ([]GetRegistrationsByUTMSourceRow, error) {
	rows, err := q.db.Query(ctx, getRegistrationsByUTMSource)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRegistrationsByUTMSourceRow{}
	for rows.Next() {
		var i GetRegistrationsByUTMSourceRow
		if err := rows.Scan(&i.Source, &i.TotalRegistrations, &i.ActiveUsers); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserAnomalyScore = `-- name: GetUserAnomalyScore :one
SELECT COALESCE(SUM(score_delta), 0)::bigint FROM anomaly_logs WHERE user_id = $1
`

func (q *Queries) GetUserAnomalyScore(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getUserAnomalyScore, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, password_hash, role, is_active, anomaly_score, created_at, utm_source FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.AnomalyScore,
		&i.CreatedAt,
		&i.UtmSource,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, password_hash, role, is_active, anomaly_score, created_at, utm_source FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.AnomalyScore,
		&i.CreatedAt,
		&i.UtmSource,
	)
	return i, err
}

const listFlaggedUsers = `-- name: ListFlaggedUsers :many
SELECT u.id, u.email, u.name, u.password_hash, u.role, u.is_active, u.anomaly_score, u.created_at, u.utm_source, COALESCE(SUM(al.score_delta), 0)::int AS total_score
FROM users u
LEFT JOIN anomaly_logs al ON al.user_id = u.id
GROUP BY u.id
HAVING COALESCE(SUM(al.score_delta), 0) >= $1
ORDER BY total_score DESC
LIMIT $2 OFFSET $3
`

type ListFlaggedUsersParams struct {
	ScoreDelta int32 `json:"score_delta"`
	Limit      int32 `json:"limit"`
	Offset     int32 `json:"offset"`
}

type ListFlaggedUsersRow struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	Name         pgtype.Text        `json:"name"`
	PasswordHash string             `json:"password_hash"`
	Role         pgtype.Text        `json:"role"`
	IsActive     pgtype.Bool        `json:"is_active"`
	AnomalyScore pgtype.Int4        `json:"anomaly_score"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UtmSource    pgtype.Text        `json:"utm_source"`
	TotalScore   int32              `json:"total_score"`
}

func (q *Queries) ListFlaggedUsers(ctx context.Context, arg ListFlaggedUsersParams) ([]ListFlaggedUsersRow, error) {
	rows, err := q.db.Query(ctx, listFlaggedUsers, arg.ScoreDelta, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFlaggedUsersRow{}
	for rows.Next() {
		var i ListFlaggedUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.PasswordHash,
			&i.Role,
			&i.IsActive,
			&i.AnomalyScore,
			&i.CreatedAt,
			&i.UtmSource,
			&i.TotalScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, name, password_hash, role, is_active, anomaly_score, created_at, utm_source FROM users ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.PasswordHash,
			&i.Role,
			&i.IsActive,
			&i.AnomalyScore,
			&i.CreatedAt,
			&i.UtmSource,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsers = `-- name: SearchUsers :many
SELECT id, email, name, password_hash, role, is_active, anomaly_score, created_at, utm_source FROM users
WHERE email ILIKE '%' || $1 || '%'
ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type SearchUsersParams struct {
	Column1 pgtype.Text `json:"column_1"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, searchUsers, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.PasswordHash,
			&i.Role,
			&i.IsActive,
			&i.AnomalyScore,
			&i.CreatedAt,
			&i.UtmSource,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsersByRole = `-- name: SearchUsersByRole :many
SELECT id, email, name, password_hash, role, is_active, anomaly_score, created_at, utm_source FROM users
WHERE email ILIKE '%' || $1 || '%' AND role = $2
ORDER BY created_at DESC LIMIT $3 OFFSET $4
`

type SearchUsersByRoleParams struct {
	Column1 pgtype.Text `json:"column_1"`
	Role    pgtype.Text `json:"role"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) SearchUsersByRole(ctx context.Context, arg SearchUsersByRoleParams) ([]User, error) {
	rows, err := q.db.Query(ctx, searchUsersByRole,
		arg.Column1,
		arg.Role,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.PasswordHash,
			&i.Role,
			&i.IsActive,
			&i.AnomalyScore,
			&i.CreatedAt,
			&i.UtmSource,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserActive = `-- name: SetUserActive :exec
UPDATE users SET is_active = $1 WHERE id = $2
`

type SetUserActiveParams struct {
	IsActive pgtype.Bool `json:"is_active"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) SetUserActive(ctx context.Context, arg SetUserActiveParams) error {
	_, err := q.db.Exec(ctx, setUserActive, arg.IsActive, arg.ID)
	return err
}

const updateUserAnomalyScore = `-- name: UpdateUserAnomalyScore :exec
UPDATE users SET anomaly_score = $2 WHERE id = $1
`

type UpdateUserAnomalyScoreParams struct {
	ID           pgtype.UUID `json:"id"`
	AnomalyScore pgtype.Int4 `json:"anomaly_score"`
}

func (q *Queries) UpdateUserAnomalyScore(ctx context.Context, arg UpdateUserAnomalyScoreParams) error {
	_, err := q.db.Exec(ctx, updateUserAnomalyScore, arg.ID, arg.AnomalyScore)
	return err
}
